kind: PersistentVolume
apiVersion: v1
metadata:
  name: sterlingb2bitoolkit-pv
  labels:
    failure-domain.beta.kubernetes.io/region: eu-gb
    failure-domain.beta.kubernetes.io/zone: lon05
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fsf-lon0501e-fz.service.softlayer.com
    path: /IBM02SEV2112072_134048/data01
